name: Clone Retrosheet Github Repository

on: 
  schedule:
      - cron: "0 1 * * *"
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Retrosheet Github Repository
      uses: actions/checkout@v2

    # This part here is cloning a second repository
    # While cloning the repository:
    #   - it clones the repo into the given `path`
    #   - it checks out the branch defined at `ref`
    - name: Clone Retrosheet Github Repository
      uses: actions/checkout@v2
      with:
        repository: chadwickbureau/retrosheet
        path: retrosheet
      
