name: Clone Retrosheet Github Repository

on: 
  schedule:
      - cron: "0 1 * * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Clone Retrosheet Github Repository
        run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/chadwickbureau/retrosheet.git
